### ISSUE TITLE
Como configurar auto deploy com vite no gh-pages

### ISSUE THREAD

**Issue by Sigerolem** [Sigerolem/github-blog#3]
### Após realizar os passos abaixo, o github fará o deploy automático do seu projeto toda vez que você realizar um *push* na branch *main* 

- Inicie um projeto com vite. O comando é `npm create vite@latest`.
- Crie um reposítorio no github para esse projeto e siga os comandos de git apresentados pelo github para ligar com seu projeto.
- Após a configuração você deve conseguir realizar *push* e ver as modificações no repositório do github.
- No seu repositório no github, vá em *Settings*.
- Na categoria *Code and automation* selecione o menu de **Pages**.
- Nessa tela você verá, na area de *Build and deployment*, a opção de escolher a origem do seu deploy.
- Escolha a opção **Github actions**.
- Na próxima tela, ao invés de escolher um *workflow*, selecione a opção  *create your own*.
- O Github agora quer que você crie  um arquivo para configurar sua nova *Action*.
- Copie o código abaixo, e faça o *Commit* do arquivo como `main.yml`
```yml
# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['main']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
       # env:
        #  VITE_VARIAVEL_TESTE: ${{ vars.VITE_VARIAVEL_TESTE }}
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload dist repository
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
``` 
- No projeto na sua máquina faça um `git pull` para sincronizar as alterações.

### Pronto! Agora a cada `git push` o github vai fazer o deploy da sua pagina.
